### PR TITLE
Starting v3.0 :D

### PR DESCRIPTION
**Pull request by LordFokas**
This is my first piece of work for 3.0

Since this will introduce a lot of breaking changes I propose we freeze the code before accepting this, and resume normal activity once I finish it, probably in 2 weeks from now.

Meanwhile PRs will potentially break everything.
I'd like to highlight that I changed all the packages to `org.nanohttpd.*`, since that's the nomenclature that's being used for everything including artifacts and I'd like to be consistent.

I'd also like to bring to your attention that I expect @ritchieGitHub and/or @elonen to have a good look at this in order to revise and accept it, as I'm not going to be so cheeky as to accept this one with the potential to break every single thing ever :p 

Also, we should probably drop the **websockets** module and merge its code into the **core** module since in a while it will start to make a lot more sense to be there. All packages have been appropriately named so that both fit together nicely, but since this messes with external tools I'm not going to do it myself.

### CODE REVIEW

**Comment by LordFokas** [comment]
@ritchieGitHub this is being a bit confusing to figure out, can you lend me a hand when you have the time? I'm delivering my course's (CS / IT Engineering) final project this week so I'm rather busy and I've had a hard time figuring what the hell is wrong by myself so far.

Travis / JUnit complain about being unable to reach class definitions, but they are there. Do we need to declare any kind of inter-module dependencies in order for this to work on Travis?

**Comment by ritchieGitHub** [comment]
Yes, this Friday i should be able to find the time

**Comment by ritchieGitHub** [comment]
the problems are fixed, checked in the changes in a branch:
https://github.com/NanoHttpd/nanohttpd/tree/LordFokas-development

The problems where caused by the different package names, probably your IDE did not refactor them correctly. Specially the service loader config files. nor the build works

**Comment by ritchieGitHub** [comment]
https://travis-ci.org/NanoHttpd/nanohttpd/builds/158740783 
build success.

**Comment by LordFokas** [comment]
Oh nice, thanks

**Comment by LordFokas** [comment]
@ritchieGitHub I'll close this and merge the branches so that we can get future PRs to stop conflicting until 3.0.0 is released.

**Pull request closed without merging**
