### PR TITLE
Added HTTP session for nanohttpd

### PR DESCRIPTION
**Pull request by pathikdevani**
here i add http session for nanohttpd. session store in memory(now).

### CODE REVIEW

**Comment by matthieu-labas** [comment]
1. Fix travis compilation problems
2. Is Java8 really necessary?
3. A new class defeats the whole purpose of NanoHTTPD being a single-class HTTP server

**Comment by LordFokas** [comment]
@matthieu-labas 
1) explain??
2) DEFINITELY NOT. If it weren't for security and stability reasons and the fact that Java 7 has better generics we'd be on 6 or 5.
3) v3.0.0 will break everything into individual class files anyways, so meh :p

**Comment by matthieu-labas** [comment]
1) Travis is complaining about several files that won't compile, I think it should be fixed (but then, I'm not too familiar with the whole testing platform thing)
2) Totally agree. The lower it can be, the better. Compilation can be done by a Java8 compiler anyway
3) Noooooooooooooo ;) Well, I guess at some point packing it all in a single .java file makes it difficult to maintain (I'm realizing I said "class" when I meant "file").

I'm curious to see how v3 will be. You're keeping the suspense high :)

**Comment by LordFokas** [comment]
You can take a look here https://github.com/LordFokas/nanohttpd/tree/development :)

**Comment by LordFokas** [comment]
About point 2, we have the Java 1.1 version for really really so-backwards-it-almost-full-circles-back-into-the-future-compatibility. Keeping the Java version low is good so that a wide amount of users can have it, but it doesn't mean we can't bump up to 8 if we decide to, say, use Lambdas, because we totally would if it gave us any design advantages.

As for 3, when you get to the point when you have multiple named non-static inner classes you know you're treading the land of bad design and maintenance nightmares, but we were way past that point already with multiple inner classes inside other inner classes in a **5 thousand line** file. Whenever I tried to debug or implement new stuff in it I kept losing track what class I was looking at and everything nasty it implies. But don't worry about the neat single-file packaging, we can still build it into a jar which is a single file which you can link to any project, so it's still ok (plus it becomes a readonly lib, so it's actually a win-win) :)

**Comment by matthieu-labas** [comment]
Yes, Java 8 interface defaults would probably be interesting, given a lot of functionalities are exposed through interfaces. Thinking about it, you could actually do that for v3, as everything will be broken down anyway. Those still using older Javas could maintain branches (thanks open source ;)).

And for the single-file java, well, as you said, at some point you should choose if you want to keep it minimal and low in functionalities, or make it evolve to a maintainable piece of software. I can't blame you because it just makes sense :)

**Comment by elonen** [comment]
My 20 eurocents.. For me, minimalism was the whole point of starting the
project in the first place. If I would've been happy using a jar, I'd
probably gone with Jetty or some other big package.

Unless NanoHTTPD has evolved into a much more featureful project than the
others (don't know!), I personally don't really see much sense in turning
it into yet another big server. For me, minimalism and
simple integration have always its main offerings. Therefore, cleaning up /
condensing the code with Lambdas etc. sounds good to me, feature creep
and jar packaging not so much.

Of course, I don't really develop it anymore, so if people really want ever
more features like the full chunking, tls, websockets, http2.0 etc. - and
don't care about minimalism - I guess split files and jar would be a viable
way ahead.

**Comment by LordFokas** [comment]
I don't think this is ever going anywhere...

**Pull request closed without merging**
