### PR TITLE
All files merged in one single class. Kind like the NanoHTTPD.

### PR DESCRIPTION
**Pull request by BrunoEberhard**
I really like the NanoHTTPD. So I wanted to try out the web sockets too. There I found the interfaces a little confusing. I tried to condense the whole thing in one class. Like it was done in NanoHTTPD. Of course there is still a problem if someone wants to use SimpleWebServer in combination with web sockets.

### CODE REVIEW

**Comment by elonen** [comment]
This is now merged with the current *master* on branch *BrunoEberhard-SingleClassServer*.
@ritchieGitHub, any opinions on this aggregation?

**Comment by ritchieGitHub** [comment]
torn between ....  on one side it fits the strategy, on the other it makes it less manageble. I see the one class principle as a way to keep the project small (nano). So yes, I think it's the way to go even if I would never do that in any other project.

**Comment by elonen** [comment]
My sentiments exactly. Let's go with this. Since compactness is pretty much the main point of the project, keeping it easy to digest / nano (in file count, and even syntax) should be very high on the priority list, even if it means some compromises.

**Comment by elonen** [comment]
Closing this request in favor of #176, which rebases these changes against current master.

**Pull request closed without merging**
