### PR TITLE
Added gradle build support

### PR DESCRIPTION
**Pull request by Josh-Larson**
Adds optional gradle support, without breaking the existing maven build system

### CODE REVIEW

**Comment by LordFokas** [comment]
I like this. BUT. Do we **REALLY** need to have one gradle file per module?
This might make things more complicated once 3.0 rolls out because there will be plenty of modules being changed...

**Comment by Josh-Larson** [comment]
Technically no, could use source sets to compile different modules, although that'll be a rather complicated build file.  For the most part, all you need to do is copy and paste the build.gradle to a new module, and any changes to the source won't require an update to the build file.

In what way do you imagine they'll change?

**Comment by LordFokas** [comment]
I don't know, I don't really know much about gradle. Or maven, for that matter. And as of now I'm the only NanoHTTP organization member still active, so I need to keep this kind of thing as simple as possible, not just for me, but also for other people who really aren't much into build systems.

**Comment by Josh-Larson** [comment]
I understand.  I'll be relying on this project more and more long-term, so I'm interested in helping out however I can.

**Comment by LordFokas** [comment]
In that case, should I ever need to restructure the build systems (for god knows what reasons) I'll call you to give me a hand :p

**Comment by Josh-Larson** [comment]
I can do that (and have done that before).

**Pull request merged**
