### PR TITLE
Single class websocket server (rebase of #166)

### PR DESCRIPTION
**Pull request by elonen**
This is a rebased version of #166 . Unit tests seem to pass and "Simple Web Socket Client" on Chrome works on echo server, but could you still review @BrunoEberhard and @ritchieGitHub that everything looks OK?

### CODE REVIEW

**Comment by ritchieGitHub** [comment]
As far as ii can see it looks good

**Comment by ritchieGitHub** [comment]
ok, just wrote a test case in the master branch. And tested if it still works in this pull and yes! ready to merge!

**Comment by BrunoEberhard** [comment]
Looks good to me. I was a little bit suprised to find jetty imports but thats ok as its only for test scope.

**Comment by ritchieGitHub** [comment]
It was the simplest websocket client I could find ;-)

**Pull request merged**
