### PR TITLE
3rd Phase of v3.0.0 - Pluginization

### PR DESCRIPTION
**Pull request by LordFokas**

### CODE REVIEW

**Comment by LordFokas** [comment]
Aaaaaand I made all the tests blow up. Again. Damn! :sob:

**Comment by ritchieGitHub** [comment]
when you do a local maven build, the same errors should occur. If you have local maven problems, maybe I can help?

**Comment by LordFokas** [comment]
The thing is I don't have a local maven.
And my test suite (JUnit in eclipse) always has ~42 errors and ~25 failures even if everything passes on Travis, thus why I'm using PRs to validate my stuff.

**Comment by LordFokas** [comment]
I got maven running.
Looks like all of these are BindExceptions, as in, the address is already in use.
We may have an HTTP cleanup issue here (one test errors, all others fail with JVM_Bind errors)

**Comment by ritchieGitHub** [comment]
installing maven is just a lokal unzip ;-) and most IDE's have a integrated one. I use eclipse and it is really easy to use.  What IDE do you use?

**Comment by LordFokas** [comment]
I'm using Eclipse Mars

**Comment by ritchieGitHub** [comment]
ok, i will write you a small manual (tonight or tomorrow)

**Comment by LordFokas** [comment]
I have it working by now. But something is terribly wrong with the code, minor structural changes broke **A LOT** of tests, and I can't figure out what it was :open_mouth:

**Comment by ritchieGitHub** [comment]
I will try to find some time to help this evening.

**Comment by LordFokas** [comment]
I might drop this PR and then push changes testing locally with maven.

**Comment by LordFokas** [comment]
And I just realized that testing locally with windows is utter and completely irrelevant because everything fails anyways. I must upgrade to an OS with a decent temp file system :(

**Pull request closed without merging**
