### PR TITLE
Fixed a bunch of warnings (from Eclipse)

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by elonen** [comment]
Looks good, but one question: are there any alternatives to these serialVersionUID strings?
The aestheticist in me whimpers in pain...

**Comment by ritchieGitHub** [comment]
not really, only alternative is not to be serializable ....

**Comment by elonen** [comment]
Gah, serializing and version numbering the exceptions seems kind of overkill...
Oh well, warnings are nasty, let's just merge this.

**Comment by elonen** [comment]
Done, thank you @vorburger !

**Pull request merged**
