### PR TITLE
Workarround for decodeParms where Duplicate Keys are encountered.

### PR DESCRIPTION
**Pull request by roloreaper**
This code will make the key have a comma separated list of values for the parameter duplicated!

### CODE REVIEW

**Comment by LordFokas** [comment]
What happens when you send the server duplicated keys with comma-separated values? I'm guessing they become impossible to parse. It would be better to store them in a list, but then key access would become a lot more complicated...

To be honest in the current state it seems a bit like an half-assed solution (although better than what we have) and I think we should either have all or none of it. We'll have to think this through and discuss the subject, including you @roloreaper. Also thank you for coming up with this (twice, apparently :p )

**Comment by roloreaper** [comment]
"(twice, apparently :p )" Yes I delete the fork on my side and obviously was not very please. 
Also very new to using git so hence the failed first Pull request was closed prematurely

**Comment by LordFokas** [comment]
@ritchieGitHub you probably have read this already, but I'd like to get some input from you on this when possible.

**Comment by ritchieGitHub** [comment]
I think the list would make it more complicated, what about adding them as separate parameter with a counter suffix that never would be added in other cases. like:
```
"parameter"="value"
"parameter@(1)"="value of duplicate 1"
"parameter@(2)"="value of duplicate 2"
"parameter@(3)"="value of duplicate 3"
```

**Comment by roloreaper** [comment]
Actually was thinking. If a list of lists was sent it would make one really long list.
key1=1,3,2,12
key1=55,22,44,33


result would be "key1"="1,3,2,12" +", " +"55,22,44,33"
hence "key1" = "1,3,2,12,55,22,44,33"

> What happens when you send the server duplicated keys with comma-separated values? 
it would actually become one long list of values.

I'm not sure what the use case is for sending multiple parameters with the same key with different list values.

I do see the senario where the form has a checkbox group and the values will be ticked in the group and submitted but I truely don't see any usecase where the groups will be sharing the same key!

**Comment by LordFokas** [comment]
The thing is, there may be values that have to be parsed (like dates and such), and by concatenating them with another marker (comma) you make them potentally impossible to parse.

I'd deprecate the parameter map and create a class where:
`String get(String param, int index)` finds the key in a list index;
`String get(String param)` returns `get(param, 0)`;
`List<String> list(String param)` returns a list of all values under that key;
`int count(String param)` returns the amount of values for that key.

For simple K->V it would essencially be just another map, but for more specialized applications it would provide all the bells and whistles without being invasive or reducing performance...

**Comment by roloreaper** [comment]
A list of Lists can work. 
And it will not be a lot of work.
And an overloaded method that the old one will use still limits duplication of the parsing of parameters!

**Comment by ritchieGitHub** [comment]
@LordFokas that was also my first reaction and then I thought of all the existing code that has to change and the complication of the simple things. What about changing the map value to CharSequence, then all the normal strings can be just strings, and we create a implementation of CharSequence (e.g. CharSequenceIterator), that behaves as a iterator in a linked list? 

CharSequenceIterator would behave like a string at the current position, but has an additional next() method that would move the current position to the next value.

**Comment by LordFokas** [comment]
You can't cast CharSequence to String, so devs will have to update anyways, the difference would be minimal, except changing the map value to CharSequence would cause more confusion that changing the param map to another class, say `Parameters` ... we can make it implement `Map<String, String>` if you want to, as that might ease the updating (no actual code changes required on fetching single parameters) provided we implement the methods I suggested above (because `get(key)` would still fetch a single value or null)...

**Comment by ritchieGitHub** [comment]
Thats a good argument, one would need to use the toString() to get to the string, also bad .... I think there is no other option left than the one you proposed, it just fustrating that a very special case has such an infulence on the normal case.

**Comment by ritchieGitHub** [comment]
Maybe take the advantage fram the disadvantage, and add methods like asInt() asLong() asString()..... The there would be a use for the normal case 😄

**Comment by LordFokas** [comment]
There's no need to use toString(). All values are still strings, and it's still up to the dev to do all the conversions. It still behaves like a map, exactly like the normal use case.
So, devs on the 'normal' use case are still using the same code, and for the special case there is little adaptation needed. I believe that to be the most reasonable approach.
Adding conversion getters (as int, string, long) would be useless overhead because most users wouldn't care for it, especially when you have a getter that gives you strings.

**Comment by ritchieGitHub** [comment]
I men't the toString in context of the charseq.

Do as you think is right, I do not have the code in reach and am just argumenting from memory 😄. At the moment I am deep in other projects and I trust you do the right thing. 

When it time to release, I will browse over the changes and we can discuss them then, if I find something problematic.

**Comment by roloreaper** [comment]
@LordFokas 
Why does the method take in a Map and Not return an object.
Why not leave my hack for the current decode parameters. Deprecate the method with a See Also 
And leave the old method for a few releases.

Introduce an new actualy returns the new better implementation. This will return a better object instead of the void!

**Comment by roloreaper** [comment]
@ritchieGitHub @LordFokas 
Please review new changes

**Comment by LordFokas** [comment]
@roloreaper I'm sorry, I've been quite busy lately and ritchie is away for a while for personal reasons...
It may take a while but it'll be reviewed and tested, eventually. I'm usually all straight-to-the-point so once I get to do it you'll notice :p

**Comment by ritchieGitHub** [comment]
@LordFokas I think it's ok.
@roloreaper  appropriate Unit tests are missing, as soon as you write a unit test we will include you PR.

**Comment by LordFokas** [comment]
@ritchieGitHub I'll leave this in your hands then, once you see appropriate tests coming in merge it ;)

**Comment by LordFokas** [comment]
@ritchieGitHub once you find this to be properly tested feel free to merge it.
This isn't that big of a problem that we'd find ourselves putting a lot of resources into it but if we find it to be insufficient we can properly refactor it along with all the breaking changes in 3.0 ... until then this little hack will have to do.

**Comment by LordFokas** [comment]
Closed by #330

**Pull request closed without merging**
