### PR TITLE
all changes needed to make the project releaseable

### PR DESCRIPTION
**Pull request by ritchieGitHub**
is did a 2.1.1 release to central of the current state, to test the system.
the distribution scm ur has to be changed to the main repo (for now it is on my fork)

### CODE REVIEW

**Comment by elonen** [comment]
I have to admit I have no experience on these modern Java build/dependency repositories. One thing to notice, however: the domain nanohttpd.com is owned by @psh who has left the project, so maybe it's better to stick with the legacy fi.iki.elonen package chain?

**Comment by ritchieGitHub** [comment]
That's not so easy the domain must be a real one. And the domain has to be owed by a project member. But I just got the domain "nanohttpd.org" registered (was not so expensive) I will put it on my server, could you add me as a organisation owner. Then I can get the central permission for "nanohttpd.org"

**Comment by ritchieGitHub** [comment]
And do not forget to add yourself to the developers list in the pom.

**Comment by elonen** [comment]
elonen.iki.fi does in fact exist (it was the original home of the project till 2012 or so), but yes, org.nanohttpd is compact, and even better than .com.

**Comment by ritchieGitHub** [comment]
ok, but it has no http server on it. at lease the browser does not connect.

**Comment by elonen** [comment]
I could easily add a subdomain, but org.nanohttpd is actually nicer.
Short, clear and more "org".

**Pull request merged**
