### PR TITLE
Add Gradle Support (+ Gradle Wrapper), AppServer mappings improvement

### PR DESCRIPTION
**Pull request by decoded4620**
Added Gradle Support with Wrapper Inclusion. This is a NON-code change, however running tests and publishing maven artifacts can be done in parallel, with Java Fork Option enabled.

This is extremely fast in comparison with running tests in maven, as the entire project is built across several threads rather than just a single thread.

Allow External Mappings to be added to AppServer (thus we can instantiate and configure instances of an app server using composition, with external RouteMapping instances.

This should also support the new Refactoring roadmap. Including gradle support is a huge win, I hope you'll accept this contribution to this AMAZING project!

Cheers

### CODE REVIEW

**Comment by ritchieGitHub** [comment]
Sorry but gradle support is not a goal of the project, just use the maven -T and you have a multy thread build. There are many plugins doing there task like checking style formatting the java files and on. Also the releasing is done over maven so sorry out of scope.

**Comment by decoded4620** [comment]
Totally understandable. Gradle is replacing maven in most industrial solutions, so I figured, worth a try.
Would you point me to the road map which you speak of so I can contribute to goals that you DO have!?

Thanks!

Decoded

**Comment by ritchieGitHub** [comment]
One of the main goals is to stay small, over the last year or so a lot of code was added. The big question is can It be written in a more compact way without making it unreadable?

Another point is the coverage by test cases, unit tests are also very welkom.

**Comment by decoded4620** [comment]
Awesome! As I continue to use the framework, I'll look for improvements and test cases that satisfy these goals.... I'll enjoy the gradle upgrade locally for myself since my entire project eco system is Gradle.

Cheers!

**Pull request closed without merging**
