### PR TITLE
Issue #214 - Nanolets condensed in a single file

### PR DESCRIPTION
**Pull request by vnnv**
I made a new pull request. Here is the "Nanolets" using static new-xx methods, and almost everything is condensed in a single file. 
There are 2 files: 
RouterNanoHTTPD.java - the main logic and utils.
AppNanolets.java - the example showing how to use this feature.

### CODE REVIEW

**Comment by vnnv** [comment]
:) any progress here?

**Comment by ritchieGitHub** [comment]
as planned I will review an convert to a module next weekend. One question in front, are unit tests included? If not please provide some, I will try to extend them to a good coverage.

**Comment by vnnv** [comment]
I'll try to do some

**Comment by ritchieGitHub** [comment]
ok it is in the master, still have to do some refactorings and tests but it is looking good ;-)

**Pull request merged**
