### PR TITLE
Enhansment #216 - Integration with apache.commons.fileupload enhancement 

### PR DESCRIPTION
**Pull request by vnnv**
Please review the code.

### CODE REVIEW

**Comment by ritchieGitHub** [comment]
sorry, other projects pull on me, it will take another week...

**Comment by vnnv** [comment]
:) Any chance to review this soon?

**Comment by ritchieGitHub** [comment]
will be integrated this weekend, the apache commons upload must be pluggable and have no direct dependency.  So the basic jar loads without any other dependsies (to keep it nano). I will see if I find a nice way to achieve this.

**Comment by ritchieGitHub** [comment]
@vnnv I have a problem with the unit test and no more time today. Could you take a look what i did wrong? 

fi.iki.elonen.TestNanoFileUpLoad.testPostWithMultipartFormUpload()

the test is Ignored because a timeout happens

**Comment by ritchieGitHub** [comment]
solved, the server was not ready. started the test to early. now 100% test coverage

**Pull request merged**
