### PR TITLE
Add simple router example. Issue #214 - NanoHTTPD uri router

### PR DESCRIPTION
**Pull request by vnnv**
Please review. It is a simple routing for NanoHTTPD. 
All files are in its own package to keep things tidy.

### CODE REVIEW

**Comment by ritchieGitHub** [comment]
@elonen what do you think I like the thing here ;-) lets call them nanolets? we could make an own module like with the websockets. of cource everythng should go into one class ;-)

**Comment by thanthos** [comment]
@vnnv You faced the same issue with the Respond object. Have to resort to wrapping the nano response within the newly created response.

I like they way you introduced the path in the addMapping as it allow the implementor to provide or change the path without changing the response result. ( It is a why didn't I think of it moment). I did it with 2 Classes 1Interface and 1ENUM. Not considering other Tools/AddOn

**Comment by vnnv** [comment]
It will be good if there is a method to create Response object outside of nanoHTTPD server. Then this wrapper class can be avoided.

**Comment by thanthos** [comment]
I would like to share my version. Can you grant me access to push in?

**Comment by vnnv** [comment]
You should make new pull request.

**Comment by elonen** [comment]
Ok, back in business... Nanolets is a nice name @ritchieGitHub , and I also think this would be best stuffed into a minimized one-file format like Websockets and core. In any case, this is definitely a useful example.

`RouterResponse` seems superfluous; if `NanoHTTPD.Response`'s protected constructor is a problem we should either open it up or inherit `RouterResponse` if extra features are required.

What exactly is the relationship between pull request #218 and this? Full alternative implementations for a router? Looks like #218 doesn't support URI path parameters (http://example.com/{variable}/someprop).

**Comment by vnnv** [comment]
If NanoHTTPD.Response is public or there is a method in NanoHTTPD that can create an instance of NanoHTTPD.Response - RouterResponse can be removed. 
pull request #218 is from another user that want to show his aproach.

**Comment by elonen** [comment]
If the RouterResponse doesn't add any functionality, is there any reason why creating a response with    `newChunkedResponse()` or `newFixedLengthResponse()` wouldn't work? The `Response` was made protected in favor of these factory functions when chunked (non-determinate size) output was implemented.

**Comment by vnnv** [comment]
Let me see the implementation of these functions in detail

**Comment by vnnv** [comment]
I think Router Response can be replaced with NanoHTTPD.Response. 
Are you going to change it, or I have to make new pull request with the changes?

**Comment by elonen** [comment]
If you have the time, an updated pull request (i.e. just commit and
push the changes to your fork) would be very much appreciated! And all the
better if you could condense the code into one .java file while at it.

**Comment by vnnv** [comment]
Ok, I'll do it. I think I'll put the Nanolets in one file and make an sample in another. And I'll put the latest changes from my project.  Than I'll make new push.

**Comment by thanthos** [comment]
@vnnv Thanks for explain it for me. 
The intention was to create 2 distinct portions; The engine and the content. The engine is of course NanoHTTPD. The content portion will be the various implementation of the response object by the users. So by configuring the uri mapping and providing implementations for generating the responses, users should be able to go straight to producing what they want to serves. @elonen the way VNNC implement it as you can see is different. What I have basically done is extending Nano and provided it with a loader functionality to load up responses to serve based on the path. 

BTW @VNNC I may have found a way to overcome the need for the wrapping the response class. 

With reference to RouterNAnoHTTPD.serve method, if you change the URIResource.Process method to return the content instead of Response, it will do away with the need to wrap it. User implementation of your URIResponder will be decoupled from NanoHTTPD.Response. The Response will only be created in RouterNanoHTTPD.  What do you think?

>RouterResponse result = uriResource.process(urlParams, session);  //To Change
>This is where the change will be. Instead of returning a wrapper object, a byte array or 
>inputstream can be return instead. Try catch loop will determine the HTTP status returned
>
>byte b[] = uriResource.process(urlParams, session);
>res =  newFixedLengthResponse(Response.Status.OK, NanoHTTPD.MIME_PLAINTEXT, new ByteArrayInputStream(b), b.length);

@elonen. It is not that it is not supporting the URI path parameters, it defer the implementation to content builder portion.

**Comment by vnnv** [comment]
Hi @elonen 
To use NanoHTTPD.Response i need newFixedLengthResponse method to be static. 
The reason is because the "nanolets" live outside of NanoHTTPD and these classes have no connection with the server itself. 
The other approach is to extend NanoHTTPD.IHTTPSession with createResponse() to create the Response object and then return it. 
What do you think? 
I prefer not to use the try - catch suggested by @thanthos because the class must return length of the data and contentType.

**Comment by elonen** [comment]
@ritchieGitHub , we discussed changing `newXXLengthResponse` factories static in #213, where you vaguely remembered someone needing them to be non-static. This case would seem to be a good counter-example, saving some unnecessary boilerplate. Are you still definitely against making them static? Forcing the user to make custom implementation of `IHTTPSession` in cases like this seems like an unnecessary complication to me.

**Comment by thanthos** [comment]
I think the question will be how "How do we want to Use Nano?" or more specifically "How do you intent others to override the serve method to provide their functionality?"
Backgound:@VNNC and myself delegate it to another class to compose the content and return a response which in turn get sent out from the serve method. The boiler plate was to help create the necessary Response. I did suggest another approach which was to return a buffer which can be easily convert to a inputstream to create the response within the serve method. 
So allowing the creation of the response outside NanoHTTPD or its child will help with that approach. Overriding serve can only go so far. 
Perhaps you can share your thoughts with us?


 ===================================
To live is to learn.
===================================

**Comment by vnnv** [comment]
IMHO returning buffer is not enough. In that case you can not return status code and mimetype. 
The idea is to delegate the response to a class outside of NanoHTTPD. And this class must return the data, the status code and mimeType of the data. Also it must return headers, but the headers are optional. So basicly it sould return Response. A simple buffer or inputstream is not enough.

**Comment by thanthos** [comment]
May I know how you are using it, if you do not mine sharing your use case?
For me by controlling the content return (ie buffer) and the type of exception thrown when I compile the content, I can incorporate the status before the final generation of the response to return in serve. That is probably because my is pretty simple and direct. 
I am creating an Android Service with a corresponding JSON object interface. So I query it respond. It is does not need the full web server feature. 
Eg: 1) Nothing return will be either a bad request or no content. 2) Exception thrown while composing the content is an internal error. 3) Missing values from request can throw an exception to it can be handle in serve.
If it is not a response, it will still need a intermediate object with the 3 component (header, content type and content) that you mention to be process within serve. In this case we had both extended the Response because it is the most appropriate. 
Brainstorming for you:1) solve it at the mapping..... each mapping will only produce one type of content type. (Hope you will not find that I am busy body). It will probably affect how you structure your content. 2) Nano to create a "Content" object/interface that is more than a buffer, which can be use to generate the response for serve. Every one will work to create a content rather than a response. 
I would like to see how the guys think of how we should use the HTTPD. It will be an insight. Then the design can be more elegant. Thats my view. 
regards



 ===================================
To live is to learn.
===================================

**Comment by vnnv** [comment]
I have a simple method that is used to download a file. The file is identified by ID. 
If the ID is correct - the file is returned with corresponding filename and mimeType. If the ID is not correct - BAD_REQUEST is returned as status and application/json as mimeType and json object with error description. 
If exception occurd - Internal server error is returned 
So if the response method must return only content - how should I deal with the above scenario?
Also if you have rest method and the method can return application/json or application/xml depending on incoming headers you can not return just buffer. 
Your approach is ok if your method return only one type of data, but if you return the data in format requested by the user - your aproach is not enough. 
Anyway it is up to @elonen and @ritchieGitHub  to decide how newXXResopnse will be changed. 
Personaly I solved the problem for my project. But this module is intended for more general use.

**Comment by elonen** [comment]
Let's change `newXXResopnse` to static unless someone comes up with a compelling reason not to. I think allowing the users to create the Responses outside of overridden `serve()` gives the most freedom without making things too unwieldy. I'll commit the change to master and you can then remove the custom Response class from this pull request @vnnv .

**Comment by elonen** [comment]
I've committed some code to a new branch `static-new-xx`. Unfortunately, it's now giving me

```
java.lang.IncompatibleClassChangeError: Expected static method fi.iki.elonen.SimpleWebServer.newFixedLengthResponse(Lfi/iki/elonen/NanoHTTPD$Response$IStatus;Ljava/lang/String;Ljava/lang/String;)Lfi/iki/elonen/NanoHTTPD$Response;
	at fi.iki.elonen.SimpleWebServer.respond(SimpleWebServer.java:430)
	at fi.iki.elonen.SimpleWebServer.serve(SimpleWebServer.java:482)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:746)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:168)
	at java.lang.Thread.run(Thread.java:745)
```

...when testing the SimpleWebServer, which I would suggest some binary dependencies if I understand correctly. @ritchieGitHub : can't find any `.jar`s in the project tree, but is it possible Maven downloads some classes from somewhere..??  Ideas / fixes welcome.

**Comment by elonen** [comment]
Turns out SimpleWebServer currently compiles/runs against a downloaded (sonatype?) .jar version of the NanoHTTPD class, not the one in source tree. The only way I found around it was to bump the version and `mvn install`. Surely there's a better way to fix that...

Anyway, the `static-new-xx` branch now contains static versions of the Response factories. Could you rebase the pull request against it, @vnnv ?

**Comment by ritchieGitHub** [comment]
the reason is that maven takes the latest build available, so it is always best to build the whole nano tree then the builds should alway be consistent.

**Comment by elonen** [comment]
Thanks, that's what I though. But how do you do it? I tried `mvn clean
compile` which *seems* to build everything but apparently it still used the
downloaded jar.

**Comment by ritchieGitHub** [comment]
do a "clean install", compile does not generate a jar for the dependencies

**Comment by ritchieGitHub** [comment]
ok, I took all the nice features (and my own idea's) into the master. please take a look if you like it and if you have any wishes ;-) 

The main difference is that the url matching uses patterns and the code is simple in one class!

**Pull request merged**
