### PR TITLE
WebSocket refactoring

### PR DESCRIPTION
**Pull request by LordFokas**
- `NanoWebSocketServer` renamed to `NanoWSD` as discussed.
- Removed event methods from `NanoWSD` and added them under `WebSocket` as abstract methods.
- Moved WebSocket Frame debug methods (on send / receive) from `NanoWSD` into `WebSocket` with name format `debugFrame<Received|Sent>()` as empty methods, so that IDEs don't force users to override them, thus keeping users from being tempted into adding code into them. Also added Javadocs explaining they are debug methods and should not be overriden unless for debug purposes.
- Added `WebSocket.onOpen()` event method that is called right after the `WebSocket` state changes to `State.OPEN`.
- Added `WebSocket.isOpen()` method that checks the internal state.
- Made the `WebSocket` class static and abstract, detaching it from `NanoWSD`.
- Made `NanoWSD.openSocket()` abstract. This is now the only method you have to override in this class. We could even make a `WebSocketFactory` interface and pass it as a constructor argument so that in most cases `NanoWSD` doesn't even need to be extended/overriden.
- Updated all the necessary tests accordingly.

As a side note, I've set up Travis-CI and Coveralls on a test branch of my fork (LordFokas/travis) so that everything I pull request into NanoHTTPD is tested against your own tests and standards before leaving my repo. Everything went fine, so I should assume it will be ok here. I've had issues with SSL and files while testing on my machine though, so the only way I can really test this is with online integration tools.

I'd also like to point out that I might put some work into increasing the coverage after this is accepted (assuming it is accepted), provided I get a stronger grip on tests... and I feel like I'm getting the hang of it quite well :)

### CODE REVIEW

**Comment by LordFokas** [comment]
I guess this closes #242

**Comment by ritchieGitHub** [comment]
Are you interested becomming a nanohttpd developer?

**Comment by LordFokas** [comment]
That is... really flattering. Thank you.

I'll have to sleep over it a few nights, but no matter what I decide I'll tell you this: I love NanoHTTPD. I'm really glad I found it and it started me on a journey that took my skills to another level, and I have a really cool use case for it (like Nanolets, but fatter) and as such I'll keep working on it and sharing my code, no matter if I accept that invitation or not :)

Meanwhile, I'll keep the code flowing, I have a few more things I want to change, namely the way cookies are handled (that was my first PR here, actually, and I don't even know how Paul accepted that code... well, at least it worked :p ).

**Comment by ritchieGitHub** [comment]
@LordFokas at the moment we are very thin spread... We wan't to create a 2.2.0 release as soon as all major bugs are "fixed" or at least analysed. Every time we think we are near new issues come is and that eats our time... So it would be great if you could help (as you are doing) getting to a "stable" state.

**Pull request merged**
