### PR TITLE
Handling a different Map of parameters for forms in parseBody().

### PR DESCRIPTION
**Pull request by matthieu-labas**
Suggestion of correction for #365 .

### CODE REVIEW

**Comment by LordFokas** [comment]
This will conflict with upcoming 3.0.0
Manually merging will be necessary, but at least we already have the logic.
Can you create a test that fails without your fix to ensure there is no regression ever?
Thank you for the help anyways :)

**Comment by matthieu-labas** [comment]
Sure, I'll try that (good time to see how testing works ;)).

**Comment by LordFokas** [comment]
The problem with all this is that test are terribly broken... the same is happening to my 3.0 branch, and I think it comes from a long time ago here.

Something tells me there's going to be a major pain involving fixing the tests. I can smell these things miles away.

**Comment by LordFokas** [comment]
@matthieu-labas the master branch now has the first half of v3.0 implemented, which makes this PR highly incompatible.

Would you like to redo this for the new code base (and get the chance to get aquainted with the new version) or should I manually apply your logic on top of my code?

**Comment by matthieu-labas** [comment]
Thanks, I'll try to find time tomorrow. I'll keep you posted anyway if I can't. Getting to know the new thing always sounds good.

**Comment by matthieu-labas** [comment]
I just did #372 and will correct Travis checks when they pop up ;)
I'll also check how to add a test on that.

**Comment by LordFokas** [comment]
I'm going to kill this PR because it has serious conflicts and we now have a new one for the 3.0.0 code base.

**Pull request closed without merging**
