### PR TITLE
add constructor with hostname parameter to RouterNanoHTTPD

### PR DESCRIPTION
**Pull request by eseidinger**
This allows restricting access to localhost for example.

### CODE REVIEW

**Comment by ritchieGitHub** [comment]
@LordFokas please add your email adress to the .travis.yml
 file so you get notivied when the build failes (as it does after this merge)

**Comment by LordFokas** [comment]
The build WHAAAAAAT? How can a simple constructor break a build? WTF?

I don't mind adding my e-mail, but the travis gh integration told me it passed and it doesn't make sense that it didn't. I'm extremely confused.

**Comment by ritchieGitHub** [comment]
https://travis-ci.org/NanoHttpd/nanohttpd/builds/115960698
Didn't check what happend yet would be great if you would look into it.

**Comment by LordFokas** [comment]
`SEVERE: Error: java.lang.InstantiationException : fi.iki.elonen.router.RouterNanoHTTPD$UriResponder`

I'll have to dig around and see what happened there. Seems odd though.

**Pull request merged**
