### PR TITLE
fixes #25 add basic CORS support

### LINKED ISSUE #25: Request headers appear to get corrupted when using ajax post
Simple ajax post requests are handled as expected and requests reach the serve method without issue. However when attempting to set a header from javascript...

xhr.open(...);
xhr.setRequestHeader("SOAPAction", "...");
xhr.send();

The request never makes it to the serve method. Upon debugging the headers as they are read into the hash map they appear corrupted with "SOAPAction" showing as a value not a key. This issue has been identified running on android.

### PR DESCRIPTION
**Pull request by McFoggy**
Find embedded a small contribution to add a basic CORS support to NanoHttpd webserver.

I got inspired from:
* @kasakara answer in the [comment](https://github.com/NanoHttpd/nanohttpd/issues/25#issuecomment-52149315)
* @AdamBien in his [CORS project](https://github.com/AdamBien/cors)

### CODE REVIEW

**Comment by kasakara** [comment]
Thanks 

Pubudu Kasakara

**Comment by elonen** [comment]
Thank you @McFoggy. Looks solid.
A question, though: would it be better to perhaps use `String corsAllowedDomain` instead of  `boolean useCORS` in the `SimpleWebServer()` constructor, to support specifying allowed domain(s) without changing the code? And/or make `addCORSHeaders(...)` protected instead of private?

**Comment by McFoggy** [comment]
@elonen changing visibility from private to protected makes sense.
For the other proposition, what would you like to see? Instead of a boolean value that allows `*`, you'd like to receive a string parameter as program argument and set this value directly to the `Access-Control-Allow-Origin`?
I am not against it of course but this would allow to open only one domain to CORS (see this answer on [SO](http://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains)).
Not sure what is the real target/usage of SimpleWebServer. Personally I use it in development environments not in production envrionements where my CORS logic is delegated to nginx/apache or servlet application filters if I need application logic in CORS handling.

**Comment by elonen** [comment]
I believe `Access-Control-Allow-Origin ` can be either a single domain or a space separated list (see http://www.w3.org/TR/cors/#access-control-allow-origin-response-header), so a single parameter should do.

**Comment by McFoggy** [comment]
@elonen find the enhancements to allow to define origin. If you want I can rebase the branch.

**Comment by elonen** [comment]
Very nice. No need to rebase, IMO.
Any objections to merging this @ritchieGitHub ?

**Comment by kasakara** [comment]
Should be ok.

**Comment by ritchieGitHub** [comment]
no this seems is a good pul request (delivers unit tests ;-) )

**Pull request merged**
