### PR TITLE
improvements for the ssl-support branch

### PR DESCRIPTION
**Pull request by eighthave**
The commits in this pull request are based on the two commits by @artichikin in the *ssl-support* branch.  We've (@binaryparadox and me) been using these commits in our app for a bit, and the SSL/TLS/HTTPS support seems to be working fine and we'd love to see it integrated into master.   We have only been testing on Android, but various versions of Android.

The two commits by @artichikin have been rebased on top of today's master, they didn't need any changes.

### CODE REVIEW

**Comment by eighthave** [comment]
any possibility of a comment here? it would be nice to revive this and get it merged in.

**Comment by ritchieGitHub** [comment]
I think it would fit, what do you think @elonen ? But could you ( @eighthave  ) help by rebasing the commits to the current master and testing it (unit tests)?

**Comment by elonen** [comment]
Yes, I agree. Already considered this, as a matter of fact. One thing that confuses me is that the pull request seems to be pointing at the master branch instead of ssl-support. Am I misunderstanding something on the Github UI..?

**Comment by ritchieGitHub** [comment]
that probably means that the branch was created from the master, and the ssl stuff was imported into it.

**Comment by elonen** [comment]
If this is really enough code to provide usable HTTPS support, it's small enough in my opinion to be included in master for easier maintenance (and one less branch).

If @eighthave can rebase this to head and confirm it still works, I'd say let's merge.
Ideas / code for unit testing this?

**Comment by ritchieGitHub** [comment]
Full agree from my side!

**Comment by eighthave** [comment]
@elonen it is enough code to provide HTTPS, we have been using it :-)  I'd like to see it in master rather than the separate branch, so happy to hear that.  I can do a rebase quickly, but unit tests will take longer.  I have some client-side unit tests in the works, but nothing ready to merge.

**Comment by ritchieGitHub** [comment]
Tests are important but haven the SSL code inside even more, thanks for your support. All these fixes and features will make the next release a great step forward! Best provide the code first and the tests later (but please do not forget them ;-) ), because the code formatting will change and that will make merging more complicated.

**Comment by eighthave** [comment]
ok, I rebased everything.  It went smoothly, and the existing tests pass.  So at least HTTPS support didn't break anything else ;-).  I'll follow up with a pull request for some simple client side tests, but don't let me block anyone from writing tests for the HTTPS stuff :-D

**Pull request merged**
